version: '2'

services:
  nginx:
    # Alpine is a super small linux distro designed for containers.
    image: nginx:stable-alpine
    networks:
      - development
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Expose local folder to nginx to serve static bits.
      - $NGINX_HTML:/var/www/html/:ro
      # Expose configuration to nginx.
      - $NGINX_DIR/sites-enabled:/etc/nginx/conf.d:ro
      - $NGINX_DIR/sites-available:/etc/nginx/sites-available:ro
      - $NGINX_DIR/snippets:/etc/nginx/snippets:ro
    links:
      - fpm
  fpm:
    # This is built locally right now. The main docker php image doesn't have any
    # extensions installed. Its really easy to customize though.
    image: local-fpm:$PHP_TAG
    build:
      context: ./$PHP_TAG
      dockerfile: Dockerfile
    networks:
      - development
    expose:
      - "9000"
    volumes:
      # Expose the same local folders nginx sees to render php content.
      - $NGINX_HTML:/var/www/html/:rw
    links:
      - db
  db:
    image: mariadb:10.1
    env_file: mysql.env # this has a environment variable that defines the root password.
    networks:
      - development
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      # Expose data directory for persistent databases.
      - /var/lib/mysql:/var/lib/mysql:rw
      # Expose socket directory for easier connections.
      - /var/run/mysqld/:/var/run/mysqld/:rw
  redis:
    image: redis:3.2-alpine
    networks:
      - development
    expose:
      - "6379"
    ports:
      - "6379:6379"
networks:
  development:
